# STATS 6289 Statistical Deep Learning
# PyTorch
## Shuang Ma
## 09/28/2020
# Python 3

### Python objects

#### List

In [ ]:
[1,2,3]

[1, 2, 3]

####  Tuple

In [ ]:
(4,5,6,7)

(4, 5, 6, 7)

#### Sets

In [ ]:
{1,2,3,"a","t","g",4,5}

{1, 2, 3, 4, 5, 'a', 'g', 't'}

#### Dictionary

In [ ]:
a = {"d":12,"j":7,"o":99}
a["j"]

7

#### Loop and Index

In [ ]:
import numpy as np
for i in np.arange(0,1,0.2):
    print(i)

0.0
0.2
0.4
0.6000000000000001
0.8


# PyTorch
[PyTorch](http://pytorch.org/) is an open source machine learning framework. 

PyTorch provides a few key features such as:

i) A multidimensioanl **Tensor** object, similar to [numpy](https://numpy.org/) but with GPU accelleration.

ii) An optimized **autograd** engine for automatically computing derivatives

iii) A clean, modular API for building and deploying **deep learning models**

You can find more information about PyTorch by following one of the [official tutorials](https://pytorch.org/tutorials/) or by [reading the documentation](https://pytorch.org/docs/1.1.0/).

## Steps for using PyTorch

### Import torch package & check version

In [3]:
import torch
print(torch.__version__)

1.6.0


# 1. Tensor Basics

### Creating and Accessing tensors

A torch **tensor** is a multidimensional grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the **rank** of the tensor; the **shape** of a tensor is a tuple of integers giving the size of the array along each dimension.

We can initialize torch tensor from nested Python lists. We can access or mutate elements of a PyTorch tensor using square brackets.

Accessing an element from a PyTorch tensor returns a PyTorch scalar; we can convert this to a Python scalar using the .item() method:

In [ ]:
# Create a rank 1 tensor from Python list

tensor1 = torch.tensor([1,2,3,4,5,6])
print(tensor1)
print("Type tensor1:",type(tensor1))
print("Rank of tensor1:",tensor1.dim())
print("Shape of tensor1:",tensor1.shape)

# Access elements using square brackets
print()
print('tensor1[4]: ', tensor1[4])
print('type(tensor1[4]): ', type(tensor1[4]))
print('type(tensor1[4].item()): ', type(tensor1[4].item()))

# Change elements using square brackets
tensor1[0] = 99
print()
print('tensor1 after changing:')
print(tensor1)

tensor([1, 2, 3, 4, 5, 6])
Type tensor1: <class 'torch.Tensor'>
Rank of tensor1: 1
Shape of tensor1: torch.Size([6])

tensor1[4]:  tensor(5)
type(tensor1[4]):  <class 'torch.Tensor'>
type(tensor1[4].item()):  <class 'int'>

tensor1 after changing:
tensor([99,  2,  3,  4,  5,  6])


In [ ]:
# Create a two-dimensional tensor
tensor2 = torch.tensor([[1, 2, 3, 4], [99, 88, 77, 66], [123,456,789,777]])
print('Here is tensor2:')
print(tensor2)
print('Rank of tensor2:', tensor2.dim())
print('Shape of tensor2: ', tensor2.shape)

# Access elements from a multidimensional tensor
print()
print('tensor2[2, 1]:', tensor2[2, 1])
print('tensor2[2, 3]:', tensor2[2, 3])
print('tensor2[0, 0]:', tensor2[0, 0])
print('tensor2[0, 1]:', tensor2[0, 1])

# Change elements of a multidimensional tensor
tensor2[1, 1] = 111111
print() 
print('tensor2 after changing:')
print(tensor2)

Here is tensor2:
tensor([[  1,   2,   3,   4],
        [ 99,  88,  77,  66],
        [123, 456, 789, 777]])
Rank of tensor2: 2
Shape of tensor2:  torch.Size([3, 4])

tensor2[2, 1]: tensor(456)
tensor2[2, 3]: tensor(777)
tensor2[0, 0]: tensor(1)
tensor2[0, 1]: tensor(2)

tensor2 after changing:
tensor([[     1,      2,      3,      4],
        [    99, 111111,     77,     66],
        [   123,    456,    789,    777]])


### Tensor Constructors

PyTorch provides many convenience methods for constructing tensors; this avoids the need to use Python lists. For example:

- torch.zeros: Creates a tensor of all zeros
- torch.ones: Creates a tensor of all ones
- torch.rand: Creates a tensor with uniform random numbers

You can find a full list of tensor creation operations in the [documentation](https://pytorch.org/docs/1.1.0/torch.html#creation-ops).

In [ ]:
# Create a tensor of all zeros
zero = torch.zeros(2, 4)
print('tensor of zeros:')
print(zero)

# Create a tensor of all ones
one = torch.ones(2, 3)
print('\ntensor of ones:')
print(one)

# Create a 2x2 identity matrix
eyes = torch.eye(2)
print('\nidentity matrix:')
print(eyes)

# Tensor of random values
rand = torch.rand(2, 4)
print('\nrandom tensor:')
print(rand)

tensor of zeros:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

tensor of ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

identity matrix:
tensor([[1., 0.],
        [0., 1.]])

random tensor:
tensor([[0.5166, 0.4409, 0.1245, 0.3064],
        [0.9174, 0.5713, 0.5086, 0.5237]])


### Data Types

In the examples above, you may have noticed that some of our tensors contained floating-point values, while others contained integer values.

PyTorch provides a large set of numeric [datatypes](https://pytorch.org/docs/1.1.0/tensor_attributes.html#torch-dtype) that you can use to construct tensors. PyTorch tries to guess a datatype when you create a tensor; functions that construct tensors typically have a dtype argument that you can use to explicitly specify a datatype.

Each tensor has a dtype attribute that you can use to check its data type:

In [ ]:
# Let torch choose the datatype
x0 = torch.tensor([1, 2])   # List of integers
x1 = torch.tensor([1., 2.]) # List of floats
x2 = torch.tensor([1., 2])  # Mixed list
print('dtype when torch chooses for us:')
print('List of integers:', x0.dtype)
print('List of floats:', x1.dtype)
print('Mixed list:', x2.dtype)

# Force a particular datatype
y0 = torch.tensor([1, 2], dtype=torch.float32)  # 32-bit float
y1 = torch.tensor([1, 2], dtype=torch.int32)    # 32-bit (signed) integer
y2 = torch.tensor([1, 2], dtype=torch.int64)    # 64-bit (signed) integer
print('\ndtype when we force a datatype:')
print('32-bit float: ', y0.dtype)
print('32-bit integer: ', y1.dtype)
print('64-bit integer: ', y2.dtype)

dtype when torch chooses for us:
List of integers: torch.int64
List of floats: torch.float32
Mixed list: torch.float32

dtype when we force a datatype:
32-bit float:  torch.float32
32-bit integer:  torch.int32
64-bit integer:  torch.int64


We can cast a tensor to another datatype using the <u>.to() </u> method; there are also convenience methods like <u>.float() </u> and <u>.long() </u> that cast to particular datatypes:

In [ ]:
x0 = torch.eye(3, dtype=torch.int64)
x1 = x0.float()  # Cast to 32-bit float
x2 = x0.double() # Cast to 64-bit float
x3 = x0.to(torch.float32) # Alternate way to cast to 32-bit float
x4 = x0.to(torch.float64) # Alternate way to cast to 64-bit float
print('x0:', x0.dtype)
print('x1:', x1.dtype)
print('x2:', x2.dtype)
print('x3:', x3.dtype)
print('x4:', x4.dtype)

x0: torch.int64
x1: torch.float32
x2: torch.float64
x3: torch.float32
x4: torch.float64


PyTorch provides several ways to create a tensor with the same datatype as another tensor:

- PyTorch provides tensor constructors such as **torch.new_zeros()** that create new tensors with the same shape and type as a given tensor
- Tensor objects have instance methods such as **.new_zeros()** that create tensors the same type but possibly different shapes
- The tensor instance method **.to()** can take a tensor as an argument, in which case it casts to the datatype of the argument.

In [ ]:
x0 = torch.eye(3, dtype=torch.float64)  # Shape (3, 3), dtype torch.float64
x1 = torch.zeros_like(x0)               # Shape (3, 3), dtype torch.float64
x2 = x0.new_zeros(2, 3)                 # Shape (2, 3), dtype torch.float64
x3 = torch.ones(4, 5).to(x0)            # Shape (4, 5), dtype torch.float64)
print('x0 shape is %r, dtype is %r' % (x0.shape, x0.dtype))
print('x1 shape is %r, dtype is %r' % (x1.shape, x1.dtype))
print('x2 shape is %r, dtype is %r' % (x2.shape, x2.dtype))
print('x3 shape is %r, dtype is %r' % (x3.shape, x3.dtype))

x0 shape is torch.Size([3, 3]), dtype is torch.float64
x1 shape is torch.Size([3, 3]), dtype is torch.float64
x2 shape is torch.Size([2, 3]), dtype is torch.float64
x3 shape is torch.Size([4, 5]), dtype is torch.float64


Even though PyTorch provides a large number of numeric datatypes, the most commonly used datatypes are:

- torch.float32: Standard floating-point type; used to store learnable parameters, network activations, etc. Nearly all arithmetic is done using this type.
- torch.int64: Typically used to store indices
- torch.uint8: Typically used to store boolean values, where 0 is false and 1 is true.

# 2. Tensor Indexing

We have already seen how to get and set individual elements of PyTorch tensors. PyTorch also provides many other ways of indexing into tensors. Getting comfortable with these different options makes it easy to modify different parts of tensors with ease.

## Slice indexing

Similar to Python lists and numpy arrays, PyTorch tensors can be ***sliced*** using the syntax start:stop or start:stop:step. The stop index is always non-inclusive: it is the first element not to be included in the slice.

Start and stop indices can be negative, in which case they count backward from the end of the tensor.

In [ ]:
tensor_sliced = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
print(0, tensor_sliced)        # (0) Original tensor
print(1, tensor_sliced[1:3])   # (1) Elements between index 1 and 3
print(2, tensor_sliced[4:])    # (2) Elements after index 4
print(3, tensor_sliced[:3])    # (3) Elements before index 3
print(4, tensor_sliced[:])     # (4) All elements
print(5, tensor_sliced[1:4:2]) # (5) Every second element between indices 1 and 4
print(6, tensor_sliced[:-2])   # (6) All but the last 2 elements
print(7, tensor_sliced[-4::2]) # (7) Every second element, starting from the fourth-last

0 tensor([1, 2, 3, 4, 5, 6, 7, 8])
1 tensor([2, 3])
2 tensor([5, 6, 7, 8])
3 tensor([1, 2, 3])
4 tensor([1, 2, 3, 4, 5, 6, 7, 8])
5 tensor([2, 4])
6 tensor([1, 2, 3, 4, 5, 6])
7 tensor([5, 7])



For multidimensional tensors, you can provide a slice or integer for each dimension of the tensor in order to extract different types of subtensors:

In [ ]:
# Create the following rank 2 tensor with shape (2, 3)
# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7 8 9]
tensor_r2 = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print('Original tensor:')
print(tensor_r2)
print('shape: ', tensor_r2.shape)

# Get first row, and all columns. 
print('\nSingle row:')
print(tensor_r2[0, :])
print(tensor_r2[0])  # Gives the same result; we can omit : for trailing dimensions
print('shape: ', tensor_r2[1].shape)

# Get second column with all row. 
print('\nSingle column:')
print(tensor_r2[:, 1])
print('shape: ', tensor_r2[:, 1].shape)

# Get the first two rows and the last two columns
print('\nFirst two rows, last two columns:')
print(tensor_r2[:2, -2:])
print('shape: ', tensor_r2[:2, -2:].shape)

# Get every other row, and columns at index 1 and 2
print('\nEvery other row, middle columns:')
print(tensor_r2[::2, 1:2])
print('shape: ', tensor_r2[::2, 1:2].shape)

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
shape:  torch.Size([3, 3])

Single row:
tensor([1, 2, 3])
tensor([1, 2, 3])
shape:  torch.Size([3])

Single column:
tensor([2, 5, 8])
shape:  torch.Size([3])

First two rows, last two columns:
tensor([[2, 3],
        [5, 6]])
shape:  torch.Size([2, 2])

Every other row, middle columns:
tensor([[2],
        [8]])
shape:  torch.Size([2, 1])


There are two common ways to access a single row or column of a tensor: using an integer will reduce the rank by one, and using a length-one slice will keep the same rank.

In [ ]:
# Create the following rank 2 tensor with shape (3, 4)
a = torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('Original tensor')
print(a)

row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print('\nTwo ways of accessing a single row:')
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

# We can make the same distinction when accessing columns::
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print('\nTwo ways of accessing a single column:')
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

Original tensor
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Two ways of accessing a single row:
tensor([5, 6, 7, 8]) torch.Size([4])
tensor([[5, 6, 7, 8]]) torch.Size([1, 4])

Two ways of accessing a single column:
tensor([ 2,  6, 10]) torch.Size([3])
tensor([[ 2],
        [ 6],
        [10]]) torch.Size([3, 1])


Slicing a tensor returns a ***view*** into the same data, so modifying it will also modify the original tensor. To avoid this, you can use the clone() method to make a copy of a tensor.

In [ ]:
# Create a tensor, a slice, and a clone of a slice
a = torch.tensor([[1, 2, 3], [4,5,6], [7,8,9]])
b = a[0, 1:]
c = a[0, 1:].clone()
print('Before mutating:')
print(a)
print(b)
print(c)

a[0,1] = 20  # a[0, 1] and b[0] point to the same element
b[1] = 30     # b[1] and a[0, 2] point to the same element
c[0] = 40     # c is a clone, so it has its own data
print('\nAfter mutating:')
print(a)
print(b)
print(c)

print(a.storage().data_ptr() == c.storage().data_ptr())

Before mutating:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([2, 3])
tensor([2, 3])

After mutating:
tensor([[ 1, 20, 30],
        [ 4,  5,  6],
        [ 7,  8,  9]])
tensor([20, 30])
tensor([40,  3])
False


So far we have used slicing to access subtensors; we can also use slicing to modify subtensors by writing assignment expressions where the left-hand side is a slice expression, and the right-hand side is a constant or a tensor of the correct shape:

### Integer Tensor Indexing

When you index into torch tensor using slicing, the resulting tensor view will always be a subarray of the original tensor. This is powerful, but can be restrictive.

We can also use ***index arrays*** to index tensors; this lets us construct new tensors with a lot more flexibility than using slices.

As an example, we can use index arrays to reorder the rows or columns of a tensor:

In [ ]:
# Create the following rank 2 tensor with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('Original tensor:')
print(a)

# Create a new tensor of shape (5, 4) by reordering rows from a:
# - First two rows same as the first row of a
# - Third row is the same as the last row of a
# - Fourth and fifth rows are the same as the second row from a
idx = [0, 0, 2, 1, 1]  # index arrays can be Python lists of integers
print('\nReordered rows:')
print(a[idx])

# Create a new tensor of shape (3, 4) by reversing the columns from a
idx = torch.tensor([3, 2, 1, 0])  # Index arrays can be int64 torch tensors
print('\nReordered columns:')
print(a[:, idx])

Original tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Reordered rows:
tensor([[ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8]])

Reordered columns:
tensor([[ 4,  3,  2,  1],
        [ 8,  7,  6,  5],
        [12, 11, 10,  9]])




More generally, given index arrays idx0 and idx1 with N elements each, a[idx0, idx1] is equivalent to:

torch.tensor([
  a[idx0[0], idx1[0]],
  a[idx0[1], idx1[1]],
  ...,
  a[idx0[N - 1], idx1[N - 1]]
])
(A similar pattern extends to tensors with more than two dimensions)

We can for example use this to get or set the diagonal of a tensor:

In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Original tensor:')
print(a)

idx = [0, 1, 2]
print('\nGet the diagonal:')
print(a[idx, idx])

# Modify the diagonal
a[idx, idx] = torch.tensor([11, 22, 33])
print('\nAfter setting the diagonal:')
print(a)

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Get the diagonal:
tensor([1, 5, 9])

After setting the diagonal:
tensor([[11,  2,  3],
        [ 4, 22,  6],
        [ 7,  8, 33]])


One useful trick with integer array indexing is selecting or mutating one element from each row or column of a matrix:

In [ ]:
# Create a new tensor from which we will select elements
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print('Original tensor:')
print(a)

# Take on element from each row of a:
# from row 0, take element 1;
# from row 1, take element 2;
# from row 2, take element 1;
# from row 3, take element 0
idx0 = torch.arange(a.shape[0])  # Quick way to build [0, 1, 2, 3]
idx1 = torch.tensor([1, 2, 1, 0])
print('\nSelect one element from each row:')
print(a[idx0, idx1])

# Now set each of those elements to zero
a[idx0, idx1] = 0
print('\nAfter modifying one element from each row:')
print(a)

Original tensor:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Select one element from each row:
tensor([ 2,  6,  8, 10])

After modifying one element from each row:
tensor([[ 1,  0,  3],
        [ 4,  5,  0],
        [ 7,  0,  9],
        [ 0, 11, 12]])


## Boolean Tensor Indexing


Boolean tensor indexing lets you pick out arbitrary elements of a tensor according to a boolean mask. Frequently this type of indexing is used to select or modify the elements of a tensor that satisfy some condition.

In PyTorch, we use tensors of dtype torch.uint8 to hold boolean masks; 0 means false and 1 means true.

In [ ]:
tensor_boolean = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
print('Original tensor:')
print(tensor_boolean)

# Find the elements of a that are bigger than 4. The mask has the same shape as
# a, where each element of mask tells whether the corresponding element of a
# is greater than three.
mask = (tensor_boolean > 4)
print('\nMask tensor:')
print(mask)

# We can use the mask to construct a rank-1 tensor containing the elements of a
# that are selected by the mask
print('\nSelecting elements with the mask:')
print(tensor_boolean[mask])

# We can also use boolean masks to modify tensors; for example this sets all
# elements <= 6 to zero:
tensor_boolean[tensor_boolean <= 6] = 0
print('\nAfter modifying with a mask:')
print(tensor_boolean)

Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Mask tensor:
tensor([[False, False, False],
        [False,  True,  True],
        [ True,  True,  True]])

Selecting elements with the mask:
tensor([5, 6, 7, 8, 9])

After modifying with a mask:
tensor([[0, 0, 0],
        [0, 0, 0],
        [7, 8, 9]])


# 3. Reshaping Operations

PyTorch provides many ways to manipulate the shapes of tensors. The simplest example is ***.view()***: This returns a new tensor with the same number of elements as its input, but with a different shape.

We can use ***.view()*** to flatten matrices into vectors, and to convert rank-1 vectors into rank-2 row or column matrices:

In [ ]:
x0 = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print('Original tensor:')
print(x0)
print('shape:', x0.shape)

# Flatten x0 into a rank 1 vector of shape (12,)
x1 = x0.view(12)
print('\nFlattened tensor:')
print(x1)
print('shape:', x1.shape)

# Convert x1 to a rank 2 "row vector" of shape (1, 12)
x2 = x1.view(1, 12)
print('\nRow vector:')
print(x2)
print('shape:', x2.shape)

# Convert x1 to a rank 2 "column vector" of shape (12, 1)
x3 = x1.view(12, 1)
print('\nColumn vector:')
print(x3)
print('shape:', x3.shape)

# Convert x1 to a rank 3 tensor of shape (3, 2, 2):
x4 = x1.view(3, 2, 2)
print('\nRank 3 tensor:')
print(x4)
print('shape:', x4.shape)

Original tensor:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
shape: torch.Size([4, 3])

Flattened tensor:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
shape: torch.Size([12])

Row vector:
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
shape: torch.Size([1, 12])

Column vector:
tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])
shape: torch.Size([12, 1])

Rank 3 tensor:
tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
shape: torch.Size([3, 2, 2])


As a convenience, calls to ***.view()*** may include a single -1 argument; this puts enough elements on that dimension so that the output has the same shape as the input. This makes it easy to write some reshape operations in a way that is agnostic to the shape of the tensor:

In [ ]:

# We can reuse these functions for tensors of different shapes
x0 = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x1 = x0.view(-1, )
x2 = x0.view(-1, 3)

print('x0:')
print(x0)

print('x1:')
print(x1)

print('x2:')
print(x2)

x0:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
x1:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
x2:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


As its name implies, a tensor returned by ***.view()*** shares the same data as the input, so changes to one will affect the other and vice-versa:

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x_flat = x.view(-1)
print('x before modifying:')
print(x)
print('x_flat before modifying:')
print(x_flat)

x[0, 0] = 70   # x[0, 0] and x_flat[0] point to the same data
x_flat[1] = 80 # x_flat[1] and x[0, 1] point to the same data

print('\nx after modifying:')
print(x)
print('x_flat after modifying:')
print(x_flat)

x before modifying:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
x_flat before modifying:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

x after modifying:
tensor([[70, 80,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
x_flat after modifying:
tensor([70, 80,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


## Swapping Axes


Another common reshape operation you might want to perform is transposing a matrix. You might be surprised if you try to transpose a matrix with ***.view()***: The view() function takes elements in row-major order, so you **cannot** transpose matrices with .view().

In general, you should only use .view() to add new dimensions to a tensor, or to collapse adjacent dimensions of a tensor.

For other types of reshape operations, you usually need to use a function that can swap axes of a tensor. The simplest such function is .t(), specificially for transposing matrices. It is available both as a [function in the torch module](https://pytorch.org/docs/1.1.0/torch.html#torch.t), and as a [tensor instance method](https://pytorch.org/docs/1.1.0/tensors.html#torch.Tensor.t):

In [ ]:
print('Original matrix:')
print(x)
print('\nTransposing with view DOES NOT WORK!')
print(x.view(4, 3))
print('\nTransposed matrix:')
print(torch.t(x))
print(x.t())

Original matrix:
tensor([[70, 80,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Transposing with view DOES NOT WORK!
tensor([[70, 80,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Transposed matrix:
tensor([[70,  4,  7, 10],
        [80,  5,  8, 11],
        [ 3,  6,  9, 12]])
tensor([[70,  4,  7, 10],
        [80,  5,  8, 11],
        [ 3,  6,  9, 12]])



For tensors with more than two dimensions, we can use the function ***torch.transpose*** to swap arbitrary dimensions, or the ***.permute*** method to arbitrarily permute dimensions:

In [ ]:

# Create a tensor of shape (2, 3, 4)
x0 = torch.tensor([
     [[1,  2,  3,  4],
      [5,  6,  7,  8],
      [9, 10, 11, 12]],
     [[13, 14, 15, 16],
      [17, 18, 19, 20],
      [21, 22, 23, 24]]])
print('Original tensor:')
print(x0)
print('shape:', x0.shape)

# Swap axes 1 and 2; shape is (2, 4, 3)
x1 = x0.transpose(1, 2)
print('\nSwap axes 1 and 2:')
print(x1)
print(x1.shape)

# Permute axes; the argument (1, 2, 0) means:
# - Make the old dimension 1 appear at dimension 0;
# - Make the old dimension 2 appear at dimension 1;
# - Make the old dimension 0 appear at dimension 2
# This results in a tensor of shape (3, 4, 2)
x2 = x0.permute(1, 2, 0)
print('\nPermute axes')
print(x2)
print('shape:', x2.shape)

Original tensor:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
shape: torch.Size([2, 3, 4])

Swap axes 1 and 2:
tensor([[[ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11],
         [ 4,  8, 12]],

        [[13, 17, 21],
         [14, 18, 22],
         [15, 19, 23],
         [16, 20, 24]]])
torch.Size([2, 4, 3])

Permute axes
tensor([[[ 1, 13],
         [ 2, 14],
         [ 3, 15],
         [ 4, 16]],

        [[ 5, 17],
         [ 6, 18],
         [ 7, 19],
         [ 8, 20]],

        [[ 9, 21],
         [10, 22],
         [11, 23],
         [12, 24]]])
shape: torch.Size([3, 4, 2])


## Contiguous Tensors



Some combinations of reshaping operations will fail with cryptic errors. The exact reasons for this have to do with the way that tensors and views of tensors are implemented, and are beyond the scope of this assignment. However if you're curious, [this blog post by Edward Yang](http://blog.ezyang.com/2019/05/pytorch-internals/) gives a clear explanation of the problem.

What you need to know is that you can typically overcome these sorts of errors by either by calling ***.contiguous()*** before ***.view()***, or by using ***.reshape()*** instead of ***.view()***.


In [ ]:
x0 = torch.randn(2, 3, 4)

try:
  # This sequence of reshape operations will crash
  x1 = x0.transpose(1, 2).view(8, 3)
except RuntimeError as e:
  print(type(e), e)
  
# We can solve the problem using either .contiguous() or .reshape()
x1 = x0.transpose(1, 2).contiguous().view(8, 3)
x2 = x0.transpose(1, 2).reshape(8, 3)
print('x1 shape: ', x1.shape)
print('x2 shape: ', x2.shape)

<class 'RuntimeError'> view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
x1 shape:  torch.Size([8, 3])
x2 shape:  torch.Size([8, 3])


# 4.Tensor Operations

## Elementwise Operations

Basic mathematical functions operate elementwise on tensors, and are available as operator overloads, as functions in the torch module, and as instance methods on torch objects; all produce the same results:

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
y = torch.tensor([[7,8,9],[10,11,12]], dtype=torch.float32)

# Elementwise sum; all give the same result
print('Elementwise sum:')
print(x + y)
print(torch.add(x, y))
print(x.add(y))

# Elementwise difference
print('\nElementwise difference:')
print(x - y)
print(torch.sub(x, y))
print(x.sub(y))

# Elementwise product
print('\nElementwise product:')
print(x * y)
print(torch.mul(x, y))
print(x.mul(y))

# Elementwise division
print('\nElementwise division')
print(x / y)
print(torch.div(x, y))
print(x.div(y))

# Elementwise power
print('\nElementwise power')
print(x ** y)
print(torch.pow(x, y))
print(x.pow(y))


Elementwise sum:
tensor([[ 8., 10., 12.],
        [14., 16., 18.]])
tensor([[ 8., 10., 12.],
        [14., 16., 18.]])
tensor([[ 8., 10., 12.],
        [14., 16., 18.]])

Elementwise difference:
tensor([[-6., -6., -6.],
        [-6., -6., -6.]])
tensor([[-6., -6., -6.],
        [-6., -6., -6.]])
tensor([[-6., -6., -6.],
        [-6., -6., -6.]])

Elementwise product:
tensor([[ 7., 16., 27.],
        [40., 55., 72.]])
tensor([[ 7., 16., 27.],
        [40., 55., 72.]])
tensor([[ 7., 16., 27.],
        [40., 55., 72.]])

Elementwise division
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])

Elementwise power
tensor([[1.0000e+00, 2.5600e+02, 1.9683e+04],
        [1.0486e+06, 4.8828e+07, 2.1768e+09]])
tensor([[1.0000e+00, 2.5600e+02, 1.9683e+04],
        [1.0486e+06, 4.8828e+07, 2.1768e+09]])
tensor([[1.0000e+00, 2.5600e+02, 1.9683e+04

Torch also provides many standard mathematical functions; these are available both as functions in the torch module and as instance methods on tensors:

You can find a full list of all available mathematical functions in the [documentation](https://pytorch.org/docs/stable/torch.html#pointwise-ops); many functions in the torch module have corresponding instance methods on [tensor objects](https://pytorch.org/docs/stable/tensors.html).

In [ ]:
x = torch.tensor([[1, 2, 3, 4]], dtype=torch.float32)

print('Square root:')
print(torch.sqrt(x))
print(x.sqrt())

print('\nTrig functions:')
print(torch.sin(x))
print(x.sin())
print(torch.cos(x))
print(x.cos())

Square root:
tensor([[1.0000, 1.4142, 1.7321, 2.0000]])
tensor([[1.0000, 1.4142, 1.7321, 2.0000]])

Trig functions:
tensor([[ 0.8415,  0.9093,  0.1411, -0.7568]])
tensor([[ 0.8415,  0.9093,  0.1411, -0.7568]])
tensor([[ 0.5403, -0.4161, -0.9900, -0.6536]])
tensor([[ 0.5403, -0.4161, -0.9900, -0.6536]])


## Reduction Operations

So far we've seen basic arithmetic operations on tensors that operate elementwise. We may sometimes want to perform operations that aggregate over part or all of a tensor, such as a summation; these are called reduction operations.

Like the elementwise operations above, most reduction operations are available both as functions in the torch module and as instance methods on tensor objects.

The simplest reduction operation is summation. We can use the .sum() function to reduce either an entire tensor, or to reduce along only one dimension of the tensor using the dim argument:

In [ ]:
x = torch.tensor([[1, 2, 3], 
                  [4, 5, 6],
                  [7, 8, 9]], dtype=torch.float32)
print('Original tensor:')
print(x)

print('\nSum over entire tensor:')
print(torch.sum(x))
print(x.sum())

# We can sum over each row:
print('\nSum of each row:')
print(torch.sum(x, dim=0))
print(x.sum(dim=0))

# Sum over each column:
print('\nSum of each column:')
print(torch.sum(x, dim=1))
print(x.sum(dim=1))

Original tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

Sum over entire tensor:
tensor(45.)
tensor(45.)

Sum of each row:
tensor([12., 15., 18.])
tensor([12., 15., 18.])

Sum of each column:
tensor([ 6., 15., 24.])
tensor([ 6., 15., 24.])



Other useful reduction operations include **mean**, **min**, and **max**. You can find a full list of all available reduction operations in the [documentation](https://pytorch.org/docs/stable/torch.html#reduction-ops).

Some reduction operations return more than one value; for example min returns both the minimum value over the specified dimension, as well as the index where the minimum value occurs:

In [ ]:
x = torch.tensor([[1,4,7], [2,7,5],[9,6,4]], dtype=torch.float32)
print('Original tensor:')
print(x, x.shape)

# Finding the overall minimum only returns a single value
print('\nOverall minimum: ', x.min())

# Compute the minimum along each column; we get both the value and location:
# The minimum of the first column is 2, and it appears at index 0;
# the minimum of the second column is 3 and it appears at index 1; etc
col_min_vals, col_min_idxs = x.min(dim=0)
print('\nMinimum along each column:')
print('values:', col_min_vals)
print('idxs:', col_min_idxs)
 
# Compute the minimum along each row; we get both the value and location 
row_min_vals, row_min_idxs = x.min(dim=1)
print('\nMinimum along each row:')
print('values:', row_min_vals)
print('idxs:', row_min_idxs)

Original tensor:
tensor([[1., 4., 7.],
        [2., 7., 5.],
        [9., 6., 4.]]) torch.Size([3, 3])

Overall minimum:  tensor(1.)

Minimum along each column:
values: tensor([1., 4., 4.])
idxs: tensor([0, 0, 2])

Minimum along each row:
values: tensor([1., 2., 4.])
idxs: tensor([0, 0, 2])


Reduction operations reduce the rank of tensors: the dimension over which you perform the reduction will be removed from the shape of the output. If you pass keepdim=True to a reduction operation, the specified dimension will not be removed; the output tensor will instead have a shape of 1 in that dimension.

When you are working with multidimensional tensors, thinking about rows and columns can become confusing; instead it's more useful to think about the shape that will result from each operation. For example: 

In [ ]:
# Create a tensor of shape (128, 10, 3, 64, 64)
x = torch.randn(128, 10, 3, 64, 64)
print(x.shape)

# Take the mean over dimension 1; shape is now (128, 3, 64, 64)
x = x.mean(dim=1)
print(x.shape)

# Take the sum over dimension 2; shape is now (128, 3, 64)
x = x.sum(dim=2)
print(x.shape)

# Take the mean over dimension 1, but keep the dimension from being eliminated
# by passing keepdim=True; shape is now (128, 1, 64)
x = x.mean(dim=1, keepdim=True)
print(x.shape)
print(x)

torch.Size([128, 10, 3, 64, 64])
torch.Size([128, 3, 64, 64])
torch.Size([128, 3, 64])
torch.Size([128, 1, 64])
tensor([[[ 1.6104e-03, -7.5883e-02,  2.8864e-01,  ..., -1.5367e+00,
          -1.8542e+00, -3.4666e-01]],

        [[ 1.0103e+00, -7.5574e-01,  9.2218e-01,  ...,  1.0086e+00,
          -8.8967e-01, -3.4153e-01]],

        [[ 2.8484e+00, -2.0620e+00, -8.2875e-01,  ...,  3.7990e-01,
           2.8070e+00,  1.3726e+00]],

        ...,

        [[-1.4905e+00, -8.6200e-01,  6.2250e-01,  ..., -1.6397e+00,
           6.2946e-01,  1.1919e+00]],

        [[ 1.8130e+00,  1.3095e+00,  1.2870e+00,  ...,  2.1866e+00,
           4.1466e-01,  1.0333e+00]],

        [[ 1.0480e+00,  4.8501e+00,  1.6249e+00,  ...,  1.5051e+00,
          -1.6254e+00, -3.0280e+00]]])


## Matrix Operations


PyTorch provides a number of linear algebra functions that compute different types of vector and matrix products. The most commonly used are:

- torch.dot: Computes inner product of vectors
- torch.mm: Computes matrix-matrix products
- torch.mv: Computes matrix-vector products
- torch.addmm / torch.addmv: Computes matrix-matrix and matrix-vector multiplications plus a bias
- torch.bmm / torch.baddmm: Batched versions of torch.mm and torch.addmm, respectively
- torch.matmul: General matrix product that performs different operations depending on the rank of the inputs; this is similar to ***np.dot*** in numpy.

You can find a full list of the available linear algebra operators in the [documentation](https://pytorch.org/docs/1.1.0/torch.html#blas-and-lapack-operations).


Here is an example of using torch.dot to compute inner products. Like the other mathematical operators we've seen, most linear algebra operators are available both as functions in the torch module and as instance methods of tensors:

In [17]:
v = torch.tensor([1,2,3,4], dtype=torch.float32)   # Modified
w = torch.tensor([5,6,7,8], dtype=torch.float32)

print(v)
print(w)
# Inner product of vectors
print('Dot products:')
print(torch.dot(v, w))
print(v.dot(w))

# we use mm for matrix-matrix products:
x = torch.tensor([[1,2,1,2],[3,4,3,4],[5,6,5,6],[7,8,7,8]], dtype=torch.float32)
y = torch.tensor([[1,2],[3,4],[5,6],[7,8]], dtype=torch.float32)
print('\nMatrix-matrix product:')
print(torch.mm(x, y))
print(torch.matmul(x,y))  # we can also using matmul for matrix-matrix products
print(x.mm(y))

# Matrix-vector multiply with torch.mv produces a rank-1 output
print('\nMatrix-vector product with torch.mv (rank 1 output)')
print(torch.mv(x, v))
print(x.mv(v))

tensor([1., 2., 3., 4.])
tensor([5., 6., 7., 8.])
Dot products:
tensor(70.)
tensor(70.)

Matrix-matrix product:
tensor([[ 26.,  32.],
        [ 58.,  72.],
        [ 90., 112.],
        [122., 152.]])
tensor([[ 26.,  32.],
        [ 58.,  72.],
        [ 90., 112.],
        [122., 152.]])
tensor([[ 26.,  32.],
        [ 58.,  72.],
        [ 90., 112.],
        [122., 152.]])

Matrix-vector product with torch.mv (rank 1 output)
tensor([16., 36., 56., 76.])
tensor([16., 36., 56., 76.])


# 5.Broadcasting

Broadcasting is a powerful mechanism that allows PyTorch to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller tensor and a larger tensor, and we want to use the smaller tensor multiple times to perform some operation on the larger tensor.

For example, suppose that we want to add a constant vector to each row of a tensor. We could do it like this:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = torch.tensor([1, 0, 1])
y = torch.zeros_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])



This works; however when the tensor x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the tensor x is equivalent to forming a tensor vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

In [ ]:

vv = v.repeat((4, 1))  # Stack 4 copies of v on top of each other
print(vv)              # Prints "[[1 0 1]
                       #          [1 0 1]
                       #          [1 0 1]
                       #          [1 0 1]]"

tensor([[1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1]])


In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])



PyTorch broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = torch.tensor([1, 2, 3])
y = x + v  # Add v to each row of x using broadcasting
print(y)

tensor([[ 2,  4,  6],
        [ 5,  7,  9],
        [ 8, 10, 12],
        [11, 13, 15]])



The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

Broadcasting two tensors together follows these rules:

- If the tensors do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
- The two tensors are said to be compatible in a dimension if they have the same size in the dimension, or if one of the tensors has size 1 in that dimension.
- The tensors can be broadcast together if they are compatible in all dimensions.
- After broadcasting, each tensor behaves as if it had shape equal to the elementwise maximum of shapes of the two input tensors.
- In any dimension where one tensor had size 1 and the other tensor had size greater than 1, the first tensor behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](https://pytorch.org/docs/stable/notes/broadcasting.html).

Not all functions support broadcasting. You can find functions that does not support broadcasting from the official docs. (e.g. ***torch.mm*** does not support broadcasting, but ***torch.matmul*** does)

Broadcasting can let us easily implement many different operations. For example we can compute an outer product of vectors:

In [ ]:
# Compute outer product of vectors
v = torch.tensor([1, 2, 3])  # v has shape (3,)
w = torch.tensor([4, 5])     # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
print(v.view(3, 1) * w)

tensor([[ 4,  5],
        [ 8, 10],
        [12, 15]])


# 6.Running on GPU

One of the most important features of PyTorch is that it can use graphics processing units (GPUs) to accelerate its tensor operations.

We can easily check whether PyTorch is configured to use GPUs:

Tensors can be moved onto any device using the .to method.

In [2]:

import torch

if torch.cuda.is_available:
  print('PyTorch can use GPUs!')
else:
  print('PyTorch cannot use GPUs.')

PyTorch can use GPUs!



You can enable GPUs in Colab via Runtime -> Change Runtime Type -> Hardware Accelerator -> GPU.

This may cause the Colab runtime to restart, so we will re-import torch in the next cell.

We have already seen that PyTorch tensors have a dtype attribute specifying their datatype. All PyTorch tensors also have a device attribute that specifies the device where the tensor is stored -- either CPU, or CUDA (for NVIDA GPUs). A tensor on a CUDA device will automatically use that device to accelerate all of its operations.

Just as with datatypes, we can use the ***.to()*** method to change the device of a tensor. We can also use the convenience methods ***.cuda()*** and ***.cpu()*** methods to move tensors between CPU and GPU.

In [3]:
# Construct a tensor on the CPU
x0 = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print('x0 device:', x0.device)

# Move it to the GPU using .to()
x1 = x0.to('cuda')
print('x1 device:', x1.device)

# Move it to the GPU using .cuda()
x2 = x0.cuda()
print('x2 device:', x2.device)

# Move it back to the CPU using .to()
x3 = x1.to('cpu')
print('x3 device:', x3.device)

# Move it back to the CPU using .cpu()
x4 = x2.cpu()
print('x4 device:', x4.device)

# We can construct tensors directly on the GPU as well
y = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float64, device='cuda')
print('y device / dtype:', y.device, y.dtype)

# Calling x.to(y) where y is a tensor will return a copy of x with the same
# device and dtype as y
x5 = x0.to(y)
print('x5 device / dtype:', x5.device, x5.dtype)

x0 device: cpu
x1 device: cuda:0
x2 device: cuda:0
x3 device: cpu
x4 device: cpu
y device / dtype: cuda:0 torch.float64
x5 device / dtype: cuda:0 torch.float64




Performing large tensor operations on a GPU can be a lot faster than running the equivalent operation on CPU.

Here we compare the speed of adding two tensors of shape (10000, 10000) on CPU and GPU:

In [4]:

import time

a_cpu = torch.randn(10000, 10000, dtype=torch.float32)
b_cpu = torch.randn(10000, 10000, dtype=torch.float32)

a_gpu = a_cpu.cuda()
b_gpu = b_cpu.cuda()
torch.cuda.synchronize()

t0 = time.time()
c_cpu = a_cpu + b_cpu
t1 = time.time()
c_gpu = a_gpu + b_gpu
torch.cuda.synchronize()
t2 = time.time()

# Check that they computed the same thing
diff = (c_gpu.cpu() - c_cpu).abs().max().item()
print('Max difference between c_gpu and c_cpu:', diff)

cpu_time = 1000.0 * (t1 - t0)
gpu_time = 1000.0 * (t2 - t1)
print('CPU time: %.2f ms' % cpu_time)
print('GPU time: %.2f ms' % gpu_time)
print('GPU speedup: %.2f x' % (cpu_time / gpu_time))

Max difference between c_gpu and c_cpu: 0.0
CPU time: 230.80 ms
GPU time: 11.37 ms
GPU speedup: 20.31 x
